# Generated by Django 4.0.10 on 2024-06-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='max 50 characters', max_length=50, verbose_name='name of contact')),
                ('email', models.EmailField(max_length=254, verbose_name='email of contact')),
                ('subject', models.CharField(help_text='max 50 characters', max_length=50, verbose_name='subject of contact')),
                ('message', models.TextField(verbose_name='message of contact')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
