# Generated by Django 4.0.10 on 2024-06-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='user',
        ),
    ]
