# Generated by Django 4.0.10 on 2024-06-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_alter_comment_recipe_alter_comment_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='author',
        ),
    ]
